### ISSUE TITLE
例子程序在开发环境中,过滤器不生效.

### ISSUE THREAD

**Issue by yangxiaoxiao23** [icarusion/vue-vueRouter-webpack#14]

**Comment by nuintun** [comment]
@yangxiaoxiao23  ```index.vue``` 中 24 行 [NumberSeparator](https://github.com/icarusion/vue-vueRouter-webpack/blob/master/src/views/index.vue?ts=2#L24) 前面多了一个空格，删除即可！

**Comment by yangxiaoxiao23** [comment]
@nuintun  嗯嗯  是这么回事  谢谢
