### ISSUE TITLE
npm run dev报错了

### ISSUE THREAD

**Issue by princessJoanna** [icarusion/vue-vueRouter-webpack#2]
前面步骤都对了，最后npm run dev报错

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! vue-fist@1.0.0 dev: `webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-fist@1.0.0 dev script 'webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js'.
npm ERR! This is most likely a problem with the vue-fist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-fist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls vue-fist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tangjuan/vue-vueRouter-webpack/npm-debug.log
tangjuandeMacBook-Pro:vue-vueRouter-webpack tangjuan$ npm run dev

**Comment by icarusion** [comment]
建议查看一下相关npm或者node等配置和安装问题，在其他多台机器安装测试是没有问题的。

**Comment by AChaoZJU** [comment]
@icarusion  不知道您所说的配置和安装问题是什么？
