### ISSUE TITLE
可以新建router.js文件管理路由，并将routers文件夹命名为views

### ISSUE THREAD

**Issue by SirM2z** [icarusion/vue-vueRouter-webpack#4]
建议：
1. 可以新建router.js文件管理路由
   - 目前路由是写在main.js中，这样伴随着项目的扩展会导致main.js的可读性变差，可以新建router.js文件管理路由导出对象，main.js引入然后map下
2. 可以将routers文件夹命名为views
   - routers第一感觉是路由，但是打开文件夹发现里边是vue文件，才明白是页面，有点绕

最后表示感谢，作者的文章很好！

**Comment by icarusion** [comment]
thx
