### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by guopingxiao** [icarusion/vue-vueRouter-webpack#5]
前面都可以，到这里就错了。
`
$ npm run dev

> vue-vue-router-webpack@1.1.0 dev E:\git\vue-vueRouter-webpack
> webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\nodejs\node_modules\webpack-dev-server\bin\webpack-dev-server.js:17:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vue-vue-router-webpack@1.1.0 dev: `webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-vue-router-webpack@1.1.0 dev script 'webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-vue-router-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-vue-router-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-vue-router-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\vue-vueRouter-webpack\npm-debug.log
`

**Comment by icarusion** [comment]
请先确保全局安装了webpack和webpack-dev-server

**Comment by guopingxiao** [comment]
安装了

```
$ npm install webpack -g
C:\Users\gpxiao\AppData\Roaming\npm\webpack -> C:\Users\gpxiao\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
C:\Users\gpxiao\AppData\Roaming\npm
`-- webpack@1.13.2
  +-- enhanced-resolve@0.9.1
  | `-- graceful-fs@4.1.6
  +-- memory-fs@0.3.0
  | `-- readable-stream@2.1.5
  +-- node-libs-browser@0.6.0
  | `-- buffer@4.9.1
  |   `-- base64-js@1.1.2
  `-- watchpack@0.2.9
    `-- chokidar@1.6.0
      `-- async-each@1.0.1
npm install webpack-dev-server -g
C:\Users\gpxiao\AppData\Roaming\npm\webpack-dev-server -> C:\Users\gpxiao\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js
C:\Users\gpxiao\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
`-- webpack-dev-server@1.15.0
  +-- compression@1.6.2
  | +-- accepts@1.3.3
  | | `-- negotiator@0.6.1
  | +-- bytes@2.3.0
  | +-- compressible@2.0.8
  | | `-- mime-db@1.23.0
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | +-- on-headers@1.0.1
  | `-- vary@1.1.0
  +-- connect-history-api-fallback@1.3.0
  +-- express@4.14.0
  | +-- array-flatten@1.1.1
  | +-- content-disposition@0.5.1
  | +-- content-type@1.0.2
  | +-- cookie@0.3.1
  | +-- cookie-signature@1.0.6
  | +-- depd@1.1.0
  | +-- encodeurl@1.0.1
  | +-- escape-html@1.0.3
  | +-- etag@1.7.0
  | +-- finalhandler@0.5.0
  | | +-- statuses@1.3.0
  | | `-- unpipe@1.0.0
  | +-- fresh@0.3.0
  | +-- merge-descriptors@1.0.1
  | +-- methods@1.1.2
  | +-- on-finished@2.3.0
  | | `-- ee-first@1.1.1
  | +-- parseurl@1.3.1
  | +-- path-to-regexp@0.1.7
  | +-- proxy-addr@1.1.2
  | | +-- forwarded@0.1.0
  | | `-- ipaddr.js@1.1.1
  | +-- qs@6.2.0
  | +-- range-parser@1.2.0
  | +-- send@0.14.1
  | | `-- destroy@1.0.4
  | +-- serve-static@1.11.1
  | +-- type-is@1.6.13
  | | `-- media-typer@0.3.0
  | `-- utils-merge@1.0.0
  +-- http-proxy-middleware@0.17.1
  | +-- http-proxy@1.14.0
  | | +-- eventemitter3@1.2.0
  | | `-- requires-port@1.0.0
  | +-- is-glob@2.0.1
  | | `-- is-extglob@1.0.0
  | +-- lodash@4.15.0
  | `-- micromatch@2.3.11
  |   +-- arr-diff@2.0.0
  |   | `-- arr-flatten@1.0.1
  |   +-- array-unique@0.2.1
  |   +-- braces@1.8.5
  |   | +-- expand-range@1.8.2
  |   | | `-- fill-range@2.2.3
  |   | |   +-- is-number@2.1.0
  |   | |   +-- isobject@2.1.0
  |   | |   +-- randomatic@1.1.5
  |   | |   `-- repeat-string@1.5.4
  |   | +-- preserve@0.2.0
  |   | `-- repeat-element@1.1.2
  |   +-- expand-brackets@0.1.5
  |   | `-- is-posix-bracket@0.1.1
  |   +-- extglob@0.3.2
  |   +-- filename-regex@2.0.0
  |   +-- kind-of@3.0.4
  |   | `-- is-buffer@1.1.4
  |   +-- normalize-path@2.0.1
  |   +-- object.omit@2.0.0
  |   | +-- for-own@0.1.4
  |   | | `-- for-in@0.1.5
  |   | `-- is-extendable@0.1.1
  |   +-- parse-glob@3.0.4
  |   | +-- glob-base@0.3.0
  |   | | `-- glob-parent@2.0.0
  |   | `-- is-dotfile@1.0.2
  |   `-- regex-cache@0.4.3
  |     +-- is-equal-shallow@0.1.3
  |     `-- is-primitive@2.0.0
  +-- open@0.0.5
  +-- optimist@0.6.1
  | +-- minimist@0.0.10
  | `-- wordwrap@0.0.3
  +-- serve-index@1.8.0
  | +-- batch@0.5.3
  | +-- http-errors@1.5.0
  | | `-- setprototypeof@1.0.1
  | `-- mime-types@2.1.11
  +-- sockjs@0.3.17
  | +-- faye-websocket@0.10.0
  | | `-- websocket-driver@0.6.5
  | |   `-- websocket-extensions@0.1.1
  | `-- uuid@2.0.2
  +-- sockjs-client@1.1.1
  | +-- eventsource@0.1.6
  | | `-- original@1.0.0
  | |   `-- url-parse@1.0.5
  | +-- faye-websocket@0.11.0
  | +-- inherits@2.0.1
  | +-- json3@3.3.2
  | `-- url-parse@1.1.3
  |   `-- querystringify@0.0.4
  +-- stream-cache@0.0.2
  +-- strip-ansi@3.0.1
  | `-- ansi-regex@2.0.0
  +-- supports-color@3.1.2
  | `-- has-flag@1.0.0
  +-- UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta
  `-- webpack-dev-middleware@1.6.1
    +-- memory-fs@0.3.0
    | +-- errno@0.1.4
    | | `-- prr@0.0.0
    | `-- readable-stream@2.1.5
    |   +-- buffer-shims@1.0.0
    |   +-- core-util-is@1.0.2
    |   +-- isarray@1.0.0
    |   +-- process-nextick-args@1.0.7
    |   +-- string_decoder@0.10.31
    |   `-- util-deprecate@1.0.2
    `-- mime@1.3.4

```

**Comment by guopingxiao** [comment]
有两条warning:
`npm WARN webpack-dev-server@1.15.0 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.`

**Comment by icarusion** [comment]
自行解决版本问题

**Comment by guopingxiao** [comment]
webpack -v
webpack 1.13.2
