### ISSUE TITLE
启动vue-vueRouter-webpack浏览器有些报错。

### ISSUE THREAD

**Issue by 0xhhhhh** [icarusion/vue-vueRouter-webpack#7]
图传不上，就直接上代码把，就是这段，webstom也不认，

```
router.beforeEach(() = > {
    window.scrollTo(0, 0);
});

router.afterEach(() = > {}
);
```

如果把代码注释掉就没问题。

**Comment by icarusion** [comment]
https://github.com/vuejs/vue-router/tree/1.0/docs/zh-cn

**Comment by panwenhua** [comment]
npm run build 之后
图片 和字体文件路径  都多了dist
正常是dist/xxxx     现在是dist/dist/xxxx
