### ISSUE TITLE
npm run dev的时候dist里没有文件呢？

### ISSUE THREAD

**Issue by yanpengfei** [icarusion/vue-vueRouter-webpack#9]
遇到个麻烦事，需要把前端和php组合到一起，不然session没法传递，但是我看监视模式下，dist里没有打包出来的文件呢，这样通过php那边的http就读取不到文件了。

**Comment by icarusion** [comment]
npm run dev是起的webpack-dev-server的服务，不会产生文件。dist会在npm run init和npm run build时产生

**Comment by yanpengfei** [comment]
我是想用这套系统与php的apache合起来用，一开始前后全部分开开发，通过跨域设置之后，接口等是没问题，后期遇到session传递问题，就必须把前端的代码合并到后边服务上发布了，不然session的cookie没法同步过来。，看来监控编译的话，就不能用webpack-dev-server了，得自己配置一个了。

**Comment by icarusion** [comment]
session肯定是在同域下才可以服务端设置和读取。因为webpack主要解决的是前后端完全分离，所以session最好也得分离出来，可以通过header或body传递，前端维护session

**Comment by yanpengfei** [comment]
通过header或者body传递我就是感觉不太安全，cookie有个httpOnly可以用，还安全一点，还有个方法就是把session甩掉，用token来做，我又嫌麻烦，我再研究研究。

**Comment by icarusion** [comment]
是的，前后端分离下，一般就不用session用token，这和开发原生APP是一样的。如果非用session，你可以开发时用npm run dev，生产时换到同域，想办法兼容一下。

**Comment by jason5149** [comment]
webpack-dev-server运行生成的bundle.js好像是存在内存里的，我用webpack -p来生成bundle.js，但是这个文件不好调试，不知道怎么生成sourceMap文件

**Comment by yanpengfei** [comment]
我把sessionID扔到header里了，后端手动设置对应的sessionID了，暂时先这样吧，反正内部系统，以后再舍掉session换token了。
